[package]
name = "game-of-life-rs"
version = "0.2.0"
authors = ["hi_go <me@clutte.red>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
rand = "0.8.4"
strum = "0.23"
strum_macros = "0.23"