[package]
name = "lifegame-rs"
version = "0.1.0"
authors = ["hi_go <me@clutte.red>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
rand = "0.8.4"
strum = "0.23"
strum_macros = "0.23"